project:
  type: website
  output-dir: docs

website:
  title: "Neil Chaturvedi"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/neilvedi
      - icon: twitter
        href: https://twitter.com/neil_chaturvedi
format:
  html:
    theme: darkly
    css: styles.css

editor: visual

