project:
  type: website
  output-dir: docs

website:
  title: "neilvedi.github.io"
  navbar:
    right:
      - index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/neilvedi
      - icon: twitter
        href: https://twitter.com/neil_chaturvedi
format:
  html:
    theme: yeti
    css: styles.css

editor: visual

