project:
  type: website
  output-dir: docs

website:
  title: "Neil Chaturvedi"
  site-url: https://neilvedi.github.io
  description: "Neil's Corner of the Internet"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/neilvedi
      - icon: twitter
        href: https://twitter.com/starshipneil
      - icon: rss
        href: index.xml
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

